bob = User.create(first_name: "Bob", last_name: "Smith", email: "bobsmith@bob.com", password: "cake")
sally = User.create(first_name: "Sally", last_name: "Smith", email: "sallysmith@bob.com", password: "morecake")
nancy = User.create(first_name: "Nancy", last_name: "Surname", email: "email@domain.com", password: "cakeforever")
bradpitt = User.create(first_name: "Brad", last_name: "Pitt", email: "123@fourfivesix.com", password: "cakelife")

bob.books << Book.create(title: "The Republic", author: "Plato")
sally.books << Book.create(title: "Game of Thrones", author: "George RR Martin")
nancy.books << Book.create(title: "The Mystery of the Shoe on the Beach", author: "Nancy Drew")
bradpitt.books << Book.create(title: "Eat Pray Love", author: "That One Author")

bob.comments << Comment.create(book_id: 2, comment_text: "Errybody's dead!")
sally.comments << Comment.create(book_id: 1, comment_text: "Plato is dry!")
nancy.comments << Comment.create(book_id: 4, comment_text: "Who wrote this book?!")
bradpitt.comments << Comment.create(book_id: 3, comment_text: "I prefer the Boxcar Children.")
Book.first.comments << Comment.create(commenter_id: 4, comment_text: "Plato is so deep!")

bob.votes << Vote.create(book_id: 2, up_or_down: 1)
sally.votes << Vote.create(book_id: 1, up_or_down: 1)
nancy.votes << Vote.create(book_id: 1, up_or_down: -1)
bradpitt.votes << Vote.create(book_id: 1, up_or_down: 1)